# https://docs.gitlab.com/ci/runners/hosted_runners/macos/
.macos_saas_runners:
  tags:
    - saas-macos-large-m2pro
  image: macos-14-xcode-15
  before_script:
    - echo "started by ${GITLAB_USER_NAME} / @${GITLAB_USER_LOGIN}"

build:
  extends:
    - .macos_saas_runners
  stage: build
  script:
    - ./gradlew macosUniversalBinary
