name: Brew Update All The Things -- Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: macos-26
    
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3
        with:
          install: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: gradle/actions/wrapper-validation@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5
      - name: Build
        run: ./gradlew macosUniversalBinary

      - name: Upload Binaries
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          # TODO will need to work out how to sign these
          name: Macos Universal Binary
          path: 'build/bin/macos-universal/brew-update-all-the-things'
